import 'package:flutter/material.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame1Widget2.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedVectorWidget4.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedDeliveryNotAvailableWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedThumb__700_0_0_0_auto1Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedSamosaCornerWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedClosedSymbolWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedClosedonFridaysWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedCategoryWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedSahakaraNagarMainRdOutsideAxisBankEastBangaloreSHOWONMA.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedOpenTime500pm830pmWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedReviewsWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFullMenuWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/Generated18kmWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedVectorWidget3.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFeaturesWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedVectorWidget15.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedShopTimingsWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedAboutWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/Generated500pm830pmWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedAhotelisanestablishmentthatprovidespaidforlodgingonasho.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedMondayFridayWidget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedVectorWidget10.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/fooddecriptionapp/generatediphone1313pro1widget/generated/GeneratedVectorWidget.dart';

/* Component iPhone 13 / 13 Pro - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone1313Pro1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -56.992401123046875,
                right: null,
                bottom: null,
                width: 409.6256103515625,
                height: 276.0428771972656,
                child: GeneratedThumb__700_0_0_0_auto1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1;
                  double scaleX = (constraints.maxWidth * percentWidth) / 39.0;

                  double percentHeight = 0.045023696682464455;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 38.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8538461538461538,
                        translateY: constraints.maxHeight * 0.23696682464454977,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 19.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 39.0,
                child: GeneratedSamosaCornerWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05384615384615385;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.03317535545023697;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 28.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8897435897435897,
                        translateY:
                            constraints.maxHeight * 0.061611374407582936,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06153846153846154;
                  double scaleX = (constraints.maxWidth * percentWidth) / 24.0;

                  double percentHeight = 0.024881516587677725;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 21.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.04871794871794872,
                        translateY: constraints.maxHeight * 0.06516587677725119,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2())
                  ]);
                }),
              ),
              Positioned(
                left: 19.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 39.0,
                child:
                    GeneratedSahakaraNagarMainRdOutsideAxisBankEastBangaloreSHOWONMA(),
              ),
              Positioned(
                left: 19.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 39.0,
                child: GeneratedOpenTime500pm830pmWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 20.0,
                child: Generated18kmWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04358974358974359;
                  double scaleX = (constraints.maxWidth * percentWidth) / 17.0;

                  double percentHeight = 0.02132701421800948;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 18.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.04871794871794872,
                        translateY: constraints.maxHeight * 0.43483412322274884,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget3())
                  ]);
                }),
              ),
              Positioned(
                left: 163.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 20.0,
                child: GeneratedDeliveryNotAvailableWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04871794871794872;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.0;

                  double percentHeight = 0.02132701421800948;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 18.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.34102564102564104,
                        translateY: constraints.maxHeight * 0.43483412322274884,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget4())
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 28.0,
                child: GeneratedAboutWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 28.0,
                child: GeneratedReviewsWidget(),
              ),
              Positioned(
                left: 264.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 25.0,
                child: GeneratedFullMenuWidget(),
              ),
              Positioned(
                left: 12.99853801727295,
                top: 436.5,
                right: null,
                bottom: null,
                width: 342.00146484375,
                height: 0.2807048559188843,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 121.00413513183594,
                height: 0.0,
                child: GeneratedVector1Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 65.0,
                child:
                    GeneratedAhotelisanestablishmentthatprovidespaidforlodgingonasho(),
              ),
              Positioned(
                left: 26.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 310.0016174316406,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 29.0,
                child: GeneratedCategoryWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 11.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 11.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 128.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 11.0,
                child: GeneratedFrame1Widget1(),
              ),
              Positioned(
                left: 128.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 11.0,
                child: GeneratedFrame2Widget(),
              ),
              Positioned(
                left: 239.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 11.0,
                child: GeneratedFrame1Widget2(),
              ),
              Positioned(
                left: 24.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 22.0,
                child: GeneratedShopTimingsWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 310.0016174316406,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 715.0,
                right: null,
                bottom: null,
                width: 310.0016174316406,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 812.0,
                right: null,
                bottom: null,
                width: 310.0016174316406,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.035897435897435895;
                  double scaleX = (constraints.maxWidth * percentWidth) / 14.0;

                  double percentHeight = 0.016587677725118485;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 14.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.06153846153846154,
                        translateY: constraints.maxHeight * 0.7772511848341233,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget10())
                  ]);
                }),
              ),
              Positioned(
                left: 46.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 13.0,
                child: GeneratedMondayFridayWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 13.0,
                child: Generated500pm830pmWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 691.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 13.0,
                child: GeneratedClosedSymbolWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 691.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 13.0,
                child: GeneratedClosedonFridaysWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 29.0,
                child: GeneratedFeaturesWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 11.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 782.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 11.0,
                child: GeneratedFrame5Widget(),
              ),
              Positioned(
                left: 131.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 11.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 242.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 11.0,
                child: GeneratedFrame7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08205128205128205;
                  double scaleX = (constraints.maxWidth * percentWidth) / 32.0;

                  double percentHeight = 0.027251184834123223;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 23.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8641025641025641,
                        translateY: constraints.maxHeight * 0.24644549763033174,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget15())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
